# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "erector_cache"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Grockit"]
  s.date = "2012-01-10"
  s.description = "Caching for your Erector"
  s.email = "mmol@grockit.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "erector_cache.gemspec",
    "lib/erector_cache.rb",
    "lib/erector_cache/abstract_widget.rb",
    "lib/erector_cache/fragment.rb",
    "spec/erector_cache/fragment_spec.rb",
    "spec/erector_cache/widget_spec.rb",
    "spec/erector_cache_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/grockit/erector_cache"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Caching for your Erector"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_runtime_dependency(%q<lawnchair>, [">= 0.6.8"])
      s.add_runtime_dependency(%q<erector>, [">= 0.8.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.6"])
      s.add_dependency(%q<lawnchair>, [">= 0.6.8"])
      s.add_dependency(%q<erector>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.6"])
    s.add_dependency(%q<lawnchair>, [">= 0.6.8"])
    s.add_dependency(%q<erector>, [">= 0.8.1"])
  end
end

